# Generated by Django 2.2 on 2020-06-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejemplar',
            name='libro',
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='libro',
            field=models.ManyToManyField(to='biblio.Libro'),
        ),
    ]
