# Generated by Django 2.2 on 2020-05-15 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('localizacion', models.CharField(max_length=50)),
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('ejemplar', models.ManyToManyField(to='biblio.Ejemplar')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('titulo', models.CharField(max_length=50)),
                ('editorial', models.CharField(max_length=50)),
                ('paginas', models.IntegerField()),
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.Autor')),
            ],
        ),
        migrations.AddField(
            model_name='ejemplar',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.Libro'),
        ),
    ]
